### ISSUE TITLE
Mobile top nav needs some love

### ISSUE THREAD

**Issue by nvk** [coinkite/bitcoinblackfriday.org#21]
Fix wrap, margins, and maybe a Twitter icon.

![A8A7E14F-198C-403A-887B-6749712A37BC](https://user-images.githubusercontent.com/797193/140241144-a814ab9a-20d2-4adb-a4c4-ebb50129b479.jpeg)

**Comment by Smollet777** [comment]
![image](https://user-images.githubusercontent.com/41921653/140290982-df0daba8-22ab-4172-9d46-a80db76300c7.png)

**Comment by nvk** [comment]
Thx for the PR
