### ISSUE TITLE
CryptoCloaks Deal - I suck at GitHub lol

### ISSUE THREAD

**Issue by CryptoCloaks** [coinkite/bitcoinblackfriday.org#27]
Thanks for the help nvk!

Black Friday Deal:
CryptoCloaks
Store wide 10% off everything using coupon code "BlackFriday"

"title": "CryptoCloaks",
    "description": "3D printed and metal products for Bitcoin. Cases / Nodes / Mounts / Nades etc.",
    "image": "",
    "starts": "2021-11-26T10:00:30.000Z",
    "ends": "2021-12-20T10:00:30.000Z",
    "categories": ["art", "nodes","bitcoin"],
    "discount": 10,
    "url": "https://cryptocloaks.com",
    "code": "BlackFriday",
    "featured": true

**Comment by nvk** [comment]
just upload here a square picture of the product and I will add for you

**Comment by CryptoCloaks** [comment]
![20200607_162429 (1)](https://user-images.githubusercontent.com/40768388/141832452-0524b218-f679-4e58-8c4d-4cc2f2fb5f08.jpg)

This should be a good one!

**Comment by nvk** [comment]
added

**Comment by CryptoCloaks** [comment]
Thanks bro!

**Comment by nvk** [comment]
preview 
![image](https://user-images.githubusercontent.com/797193/141844704-afa40d96-aaaa-4187-b99b-56749253bc4f.png)
