### ISSUE TITLE
Can only add % discounts.

### ISSUE THREAD

**Issue by pardus79** [coinkite/bitcoinblackfriday.org#28]
Want to add a "Buy 2 Get 1 Free" deal for btcpins.com but it looks like your setup only allows for % discounts to be listed.

**Comment by nvk** [comment]
@jimbojw any chance you can tweak it so that we can put "other" instead of a number and displays "OTHER" on the ui?

**Comment by nvk** [comment]
@pardus79 add it anyways with a 100% discount for now. we can put the details there somewhere.

**Comment by pardus79** [comment]
Will do. Thanks guys.

**Comment by nvk** [comment]
all set 
![image](https://user-images.githubusercontent.com/797193/141844612-3cab50dd-e0ac-466b-80cf-f0cad9b1d21a.png)
