### ISSUE TITLE
Hodlr

### ISSUE THREAD

**Issue by HodlrSwiss** [coinkite/bitcoinblackfriday.org#33]
"title": "Hodlr Disks Stealth",
    "description": "Seed Metal Backup - All Black",
    "image": 
![1_hand](https://user-images.githubusercontent.com/61015418/142383101-75bd25ef-ca73-4c00-abf9-020f08ec1ea5.jpg)
![2_ring](https://user-images.githubusercontent.com/61015418/142383105-af1d7099-cdd1-402a-a48e-52b73e0c9333.jpg)
![3_escargot](https://user-images.githubusercontent.com/61015418/142383108-2ba19f04-c938-426c-90ba-2d3e83ebaa29.jpg)
![4_punch](https://user-images.githubusercontent.com/61015418/142383110-90c5ad70-af6b-4353-b3ab-8666b656ab36.jpg)
![5_zoompunch](https://user-images.githubusercontent.com/61015418/142383112-e8609314-18c4-4980-bc20-d64d086f219d.jpg)
![6_flower](https://user-images.githubusercontent.com/61015418/142383113-720cf55a-3be3-4ede-a3b8-833cb4141fe8.jpg)
![6b_parameters](https://user-images.githubusercontent.com/61015418/142383114-19cc9f40-ed19-4cdb-a455-0c7544726402.jpg)
![7_back](https://user-images.githubusercontent.com/61015418/142383117-6513882b-05b3-407c-9472-e30b2d6f9a81.jpg)
![8_wrench](https://user-images.githubusercontent.com/61015418/142383118-7323296e-8772-45e6-b41d-b8eb25131e29.jpg)
![9_3pack](https://user-images.githubusercontent.com/61015418/142383119-de5b7edb-d84e-4d2f-9c08-e7fe7f7b3e96.jpg)
    "starts": "2021-11-17T10:00:30.000Z",
    "ends": "2021-11-17T10:00:30.000Z",
    "categories": ["seed backup", "tools", "security"],
    "discount": "25%",
    "url": "https://hodlr.swiss/products/seed-metal-backup-hodlr-disks-stealth",
    "code": "BITCOINBF25",
    "featured": false

**Comment by nvk** [comment]
added.
