### ISSUE TITLE
Hi, we'd like to participate - happy to provide more details as required - contact: info@de-googled.com

### ISSUE THREAD

**Issue by Roverid** [coinkite/bitcoinblackfriday.org#34]
{
    "title": "Degoogled Pixel 4a (BBF 2021 edition)",
    "description": "Degoogled GrapheneOS / CalyxOS phone",
    "image": ![Piaxel4a_GrapheneOS_540x](https://user-images.githubusercontent.com/54887419/142382803-21878947-d6cb-4dfb-bdb3-eabdb3b4f250.jpg)
    "starts": "2021-11-01T10:00:30.000Z",
    "ends": "2021-11-30T10:00:30.000Z",
    "categories": ["phone"],
    "discount": "10%",
    "url": "https://de-googled.com/collections/degoogled-phones",
    "code": "no code needed, choose the Degoogled Pixel 4a (BBF 2021 edition) product",
    "featured": false
  }

**Comment by nvk** [comment]
added
