### ISSUE TITLE
Please add black friday offer

### ISSUE THREAD

**Issue by glowleaf** [coinkite/bitcoinblackfriday.org#36]
[
  {
    "title": "Genesis Culotte 3 Pack",
    "description": "Buy a pack of 3 and get one extra panty free.",
    "image": "https://georgesaoulidis.com/wp-content/uploads/2021/11/blackfridaysafeforwork.jpg",
    "starts": "2021-11-11T10:00:30.000Z",
    "ends": "2021-11-30T10:00:30.000Z",
    "categories": ["panties", "apparel"],
    "discount": "25%",
    "url": "https://pantiesforbitcoin.com/",
    "code": "NO CODE NEEDED",
    "featured": false
  },
  {
    "title": "Genesis Hipster 3 Pack",
    "description": "Buy a pack of 3 and get one extra panty free.",
    "image": "https://georgesaoulidis.com/wp-content/uploads/2021/11/blackfridaysafeforwork.jpg",
    "starts": "2021-11-11T10:00:30.000Z",
    "ends": "2021-11-30T10:00:30.000Z",
    "categories": ["panties", "apparel"],
    "discount": "25%",
    "url": "https://pantiesforbitcoin.com/",
    "code": "NO CODE NEEDED",
    "featured": false
  }
]

**Comment by nvk** [comment]
Could you submit a SFW product image for hosting here.

**Comment by nvk** [comment]
nvm, all set.

**Comment by nvk** [comment]
did this 
![image](https://user-images.githubusercontent.com/797193/142876499-67aed1e6-4328-464e-acea-1c94ccc9e742.png)
