### ISSUE TITLE
Blockstream 10% off Sitewide

### ISSUE THREAD

**Issue by dfischer15** [coinkite/bitcoinblackfriday.org#38]
{
    "title": "Blockstream 10% off Storewide",
    "description": "Multiple products",
    "image": "blockstream_black_friday_sale.jpg",
    "starts": "2021-11-26T00:00:30.000Z",
    "ends": "2021-11-28T11:59:59.000Z",
    "categories": ["hardware wallet","stickers","hats", "apparel"],
    "discount": "10%",
    "url": "https://store.blockstream.com/",
    "code": "NO CODE NEEDED",
    "featured": false
  }
![blockstream_black_friday_sale jpg](https://user-images.githubusercontent.com/94870247/142934988-2b14b433-46ac-490c-ae4d-a18658698634.jpg)
,

**Comment by nvk** [comment]
added
