### ISSUE TITLE
Please add Satoshi figure Black Friday Deal - contact is info@gobrrr.me

### ISSUE THREAD

**Issue by SomeBTChomer** [coinkite/bitcoinblackfriday.org#41]
[
{
"title": "Satoshi-Resin-Figure",
"description": "Black Friday Deal - 10% off",
"image": "https://www.gobrrr.me/ozypsoob/2021/11/cropped-PXL_20211121_132246143.PORTRAIT-scaled-1.jpg",
"starts": "2021-11-24T10:00:30.000Z",
"ends": "2021-11-28T10:00:30.000Z",
"categories": ["Art"],
"discount": "10%",
"url": "https://www.gobrrr.me/product/satoshi-by-saoulidisg/",
"code": "NO CODE NEEDED",
"featured": false
}
]

**Comment by SomeBTChomer** [comment]
In case the image link doesn't work as expected, please use the img below. I hope I have set everything correctly now.

![SatoshiBFS](https://user-images.githubusercontent.com/90603175/143037347-a20c65b2-5832-4a26-9161-49d1bed855ae.jpg)

**Comment by nvk** [comment]
added
